### PR TITLE
Add ReversalTree

### LINKED ISSUE #21: Implicit key splay tree
Hello. I have seen your implementation of splay tree data structure. I want to propose quiet different data structure - splay tree with implicit key (not sure about naming). It doesn't support finding elements by key. Instead, it allows to emulate sequence of elements and supports concatenating, splitting and reversing with log(n) complexity in average.
For better explanation refer to [this post](http://developers-club.com/posts/102364/).
You can find my implementation [here](https://github.com/kalabukdima/splay_tree/blob/master/splay.h).
It is written for c++14 and with Google style guide. I can fix it and create PR if you are interested.

### PR DESCRIPTION
**Pull request by kalabukdima**
Well, as you left my issue unanswered I decided to move on and offer a PR.
This is an container-like implementation of splay tree on implicit key data structure.
Closes #21.

### CODE REVIEW

**Review by moghya — CHANGES_REQUESTED** [review]
First of a Big Thank you for taking time to contribute to this project. This project aims to implement everything from scratch and not use any standard library, please remove dependencies of stdint,string,memory,iterator, type_traits for array use array implemented in this library.

**Comment by kalabukdima** [comment]
Oh, I forgot about not using standard library. Getting rid of memory and iterator deps would take quiet a lot of time for me. I won't be able to do it in near future, but I hope I will return and fix it later.

**Comment by moghya** [comment]
@kalabukdima Any plans of modifying this change ?
Thanks.

**Comment by kalabukdima** [comment]
Totally forgot about it. I'll try to finish it next month, if it's still needed.

**Comment by kalabukdima** [comment]
Whoops, something went wrong while trying to push my updates. Seems that I can't update this PR now, so I've created a new one: #46

**Pull request closed without merging**
